### ISSUE TITLE
读取文件失败！！

### ISSUE THREAD

**Issue by ycasd123** [luojunhui/touch-fish#10]
2022-05-07 10:21:54,828 [ 127780]   INFO - ion.wsl.WslDistributionManager - Cannot parse WSL distributions 
java.io.IOException: Failed to run C:\Windows\system32\wsl.exe --list --quiet: {exitCode=1, timeout=false, cancelled=false, stdout=
版权所有 (c) Microsoft Corporation。保留所有权利。

	at com.intellij.execution.wsl.WslDistributionManagerImpl.doFetchDistributionsFromWslCli(WslDistributionManagerImpl.java:140)
	at com.intellij.execution.wsl.WslDistributionManagerImpl.loadInstalledDistributionMsIds(WslDistributionManagerImpl.java:39)
	at com.intellij.execution.wsl.WslDistributionManager.loadInstalledDistributions(WslDistributionManager.java:129)
	at com.intellij.execution.wsl.WslDistributionManager.getInstalledDistributions(WslDistributionManager.java:61)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-07 10:22:33,620 [ 166572]   INFO - j.ide.actions.RevealFileAction - Exit code 1 
2022-05-07 10:22:35,652 [ 168604]   INFO - rationStore.ComponentStoreImpl - Saving appcn.luojunhui.touchfish.config.BookSettingsState took 116 ms

**Comment by ycasd123** [comment]
已解决。txt需要utf-8编码，转一下就好。话说log里面没有相关的记录日志啊。
